blank_issues_enabled: true
contact_links:
  - name: Ask a question / Ask for help
    url: https://github.com/FrameMuse/react-modal-global/discussions/categories/q-a
    about: Please ask and answer questions here. Use discussions instead of issues.
  - name: Community Chat
    url: https://discord.com/invite/DCUWrRhvnt
    about: Please join our Discord server to chat with the community.