# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: NPM Package Publish

on:
  release:
    types: [released]
  workflow_dispatch:
    inputs:
          version:
            description: 'Version'
            type: text
            required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm ci
      - run: |
          echo "Version: ${{inputs.version}}"
          echo "Versiona: ${{inputs.versiona}}"

  publish-current:
    needs: build
    runs-on: ubuntu-latest
    if: "!contains(inputs.version, '.')"
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
  publish-specific:
      needs: build
      runs-on: ubuntu-latest
      if: "contains(inputs.version, '.')"
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-node@v3
          with:
            node-version: 18
            registry-url: https://registry.npmjs.org/
        - run: npm ci
        - run: |
            npm publish react-modal-global@${{inputs.version}}
          env:
            NODE_AUTH_TOKEN: ${{secrets.npm_token}}
